CREATE USER 'serviceAcct'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON `wizardwarrors`.* TO 'serviceAcct'@'localhost'
REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
