DROP TABLE IF EXISTS entity_gamestats;
CREATE TABLE entity_gamestats ( 
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    TeamDeaths INTEGER NOT NULL,
    TeamKills INTEGER NOT NULL,
    PlayerLevel INT NOT NULL,
    PlayerKills INTEGER NOT NULL,
    PlayerKillsAtLevel INTEGER NOT NULL,
    TotalAllies INTEGER NOT NULL,
    TotalEnemies INTEGER NOT NULL,
    IsGameOver bit(1) NOT NULL DEFAULT b'0',
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsActive bit(1) NOT NULL DEFAULT b'1',
    PRIMARY KEY (ID)
);