name: Deploy ww-ui

on:
  push:
    branches:
      - master
    paths:
      - 'ww-ui/**/*'
  workflow_dispatch:

jobs:
  deploy-ww-ui:
    if: "!contains(github.event.head_commit.message, 'from sonastea/master')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Coolify Deployment for Frontend
        run: |
          curl --request GET "${{ secrets.COOLIFY_WW_UI_WEBHOOK }}" --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
