name: Deploy ww-srv and ww-ui

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-ww-srv:
    if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'ww-ui/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Coolify Deployment for Backend
        if: ${{ !contains(github.event.head_commit.modified, 'ww-ui/') }}
        run: |
          echo "Deploying ww-srv..."
          curl --request GET \
            --url '${{ secrets.COOLIFY_WW_SRV_WEBHOOK }}' \
            --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' \
            --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'


  deploy-ww-ui:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'ww-ui/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Coolify Deployment for Frontend
        if: contains(github.event.head_commit.modified, 'ww-ui/')
        run: |
          echo "Deploying ww-ui..."
          curl --request GET \
            --url '${{ secrets.COOLIFY_WW_UI_WEBHOOK }}' \
            --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' \
            --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
