name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-ww-ui:
    if: github.repository == 'sonastea/WizardWarriors'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          cd ww-ui
          npm install

      - name: Run Linter
        run: |
          cd ww-ui
          npm run lint

  build-ww-ui:
    runs-on: ubuntu-latest
    needs: lint-ww-ui
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd ww-ui
          npm install

      - name: Build Project
        run: |
          cd ww-ui
          npm run build
